name: TEST_release_info

on:
  push:
    branches:
     - main
    paths:
      - .github/workflows/TEST_release_info.yml
  pull_request: 
    branches:
     - main

  workflow_dispatch:


jobs:

  Building_RetroDECK:
    runs-on: ubuntu-latest
    steps:

      - name: Generate build ID
        id: generating_buildid
        run: echo "##[set-output name=build-id;]$(echo "$( git rev-parse --short HEAD )")"
      
      - uses: actions/checkout@v3

      - name: Initialize enviornment
        run: |
          git pull
          git submodule init
          git submodule update
          sudo apt install -y flatpak flatpak-builder p7zip-full xmlstarlet

      - name: Getting version info
        id: version
        run: |
          appdata="https://raw.githubusercontent.com/XargonWan/RetroDECK/main/net.retrodeck.retrodeck.appdata.xml"
          export REL_VER=$(curl -s $appdata | xmlstarlet sel -t -v "//release/@version" | head -1)
          EXPORT REL_DESC="$(curl -s $appdata | xmlstarlet sel -t -m "//release[1]" -v "description" -n | sed '1,2d;$d;s/^ */- /;/^- $/d')"

      - name: Publish the flatpak in a new release
        uses: ncipollo/release-action@v1
        with:
          tag: "${{ steps.version.REL_VER }}"
          body: |
            # Release Notes

            "${{ steps.version.REL_DESC }}"

          #artifacts: "RetroDECK.flatpak,RetroDECK-Artifact.tar.gz"
          allowUpdates: true
          prerelease: true
          draft: true
          token: ${{ secrets.TRIGGER_BUILD_TOKEN }}
          repo: RetroDECK
        continue-on-error: true